#pragma once

#include <stdint.h>

enum Motor2Phase : uint8_t {
  M2_PHASE_IDLE = 0,
  M2_PHASE_TIMED_FEED
};

enum Motor2FeedSource : uint8_t {
  M2_FEED_NONE = 0,
  M2_FEED_TCP
};

enum SystemFault : uint8_t {
  FAULT_NONE = 0,
  FAULT_ENDSTOP,
  FAULT_TENSION_TIMEOUT,
  FAULT_CYLINDER_OPEN,
  FAULT_HOSE_ABSENT,
  FAULT_BUFFER_TIMEOUT,
  FAULT_OPERATOR_STOP
};

enum AutoState : uint8_t {
  AUTO_OFF,
  AUTO_HOME_HOLD,
  AUTO_SERVO_LEAD,
  AUTO_CW,
  AUTO_CCW,
  AUTO_ENDSTOP_FAULT,
  AUTO_TENSION_FAULT,
  AUTO_CYLINDER_FAULT,
  AUTO_HOSE_FAULT,
  AUTO_BUFFER_FAULT,
  AUTO_OPERATOR_STOP
};
